222

diff --git a/MeTTa b/MeTTa
--- a/MeTTa
+++ b/MeTTa
@@ -8,6 +8,8 @@ export MeTTa=$(basename "$SCRIPT")
 export METTALOG_DIR=$(dirname "$SCRIPT")
 #echo "METTALOG_DIR=$METTALOG_DIR"
 cd "$METTALOG_DIR" || { echo "Failed to navigate to $METTALOG_DIR"; [[ "$IS_SOURCED" == "1" ]] && return 1 || exit 1; }
+should_compile=0
+never_compile=0
 
 
 # Initialize the variable to indicate whether to use the test script
@@ -89,7 +91,7 @@ add_to_list() {
 }
 
 function print_help {
-    echo " CMD: $0"
+    echo " CMD: $0 ${SWI_OPTIONS[*]} -l $METTALOG_DIR/metta_vspace/$PYSWIP_VERSION/metta_interp.pl -- --python=$python_flag ${PRE_OTHER_OPTIONS[*]} ${OTHER_OPTIONS[*]}"
     echo " Usage: $MeTTa [options] <metta-files|directories> ... [-- arg ...passed to your program...]"
     echo "        $MeTTa [options] [-o executable] -c metta-file1 -c metta-file2 ... to compile into executable ..."
     echo "        $MeTTa --help         Display this message"
@@ -145,11 +147,12 @@ function print_help {
 # Initialize variables
 SWI_OPTIONS=()
 OTHER_OPTIONS=()
+PRE_OPTIONS=()
 FLAG_WITH_ARG=false
 python_flag=enable
 LIST_OF_FILE_ARGS=()
 PYSWIP_VERSION="pyswip"
-
+wants_print_help=0
 
 
 remove_quotes() {
@@ -162,27 +165,27 @@ function handle_args {
     SKIP_TO_OTHER_OPTIONS=false
 
     for arg in "$@"; do
+
+        if [[ $SKIP_TO_OTHER_OPTIONS == true ]]; then
+            OTHER_OPTIONS+=("$arg")
+            continue
+        fi
+
+        if [[ "$arg" == "--" ]]; then
+	    OTHER_OPTIONS+=("$arg")
+            SKIP_TO_OTHER_OPTIONS=true
+            continue
+        fi
+
         arg=$(remove_quotes "$arg")  # Remove the quotes
 
+        # track file paths but keep going
         if [[ -f "$arg" || -d "$arg" ]]; then
             arg_realpath="$(realpath "$arg")"
             if [[ -f "$arg_realpath" || -d "$arg_realpath" ]]; then
                 add_to_list "$arg_realpath" LIST_OF_FILE_ARGS
             fi
         fi
-
-        if [[ $SKIP_TO_OTHER_OPTIONS == true ]]; then
-            add_to_list "$arg" OTHER_OPTIONS
-            continue
-        fi
-
-        if [[ "$arg" == "--" ]]; then
-            SKIP_TO_OTHER_OPTIONS=true
-            continue
-        fi
-
-        [[ "$arg" == "--help" || "$arg" == "-h" ]] && { print_help; EXIT_SCRIPT=0; }
-        [[ "$arg" =~ ^--dump-runtime-variables.*$ || "$arg" == "--abi-version" || "$arg" == "--version" || "$arg" == "--arch" ]] && { swipl $@; EXIT_SCRIPT=0; }
 
         if [[ "$arg" =~ ^--timeout=([0-9]+)$ ]]; then
             TIMEOUT="${BASH_REMATCH[1]}"
@@ -205,22 +208,18 @@ function handle_args {
             html_flag=false
         fi
 
+        [[ "$arg" == "--help" || "$arg" == "-h" ]] && { wants_print_help=1; EXIT_SCRIPT=0; }
+        [[ "$arg" =~ ^--dump-runtime-variables.*$ || "$arg" == "--abi-version" || "$arg" == "--version" || "$arg" == "--arch" ]] && { swipl $@; EXIT_SCRIPT=0; }
 
         [[ "$FLAG_WITH_ARG" == true ]] && { SWI_OPTIONS+=("$arg"); FLAG_WITH_ARG=false; continue; }
 
         # These options require an argument (like a filename)
         case $arg in
-            --v1)
-                PYSWIP_VERSION="pyswip1"
-                continue
-                ;;
-            --v2)
-                PYSWIP_VERSION="pyswip2"
-                continue
-                ;;
 
            --v*)
                 PYSWIP_VERSION="pyswip${arg#*v}"
+		rm -f ./Sav.MeTTaLog
+		never_compile=1
                 continue
                 ;;
 
@@ -234,6 +233,13 @@ function handle_args {
                 SWI_OPTIONS+=("$arg")
                 continue
                 ;;
+
+            ---*)
+		    DASH2="-${arg#*---}"
+                   OTHER_OPTIONS=("$DASH2" "${OTHER_OPTIONS[@]}")
+                continue
+                ;;
+
             *)
 		if [[ -f "$arg" || -d "$arg" ]]; then
 		    arg_realpath="$(realpath "$arg")"
@@ -294,13 +300,6 @@ if [[ ! -z "$DIR_OPTS" ]]; then
     handle_args $DIR_OPTS
 fi
 
-if [ -z "${EXIT_SCRIPT+x}" ]; then
-    :
-else
-    [[ "$IS_SOURCED" == "1" ]] && return "$EXIT_SCRIPT" || exit "$EXIT_SCRIPT"
-fi
-
-
 #echo "Debug: SWI_OPTIONS: ${SWI_OPTIONS[@]}"
 #echo "Debug: LIST_OF_FILE_ARGS: ${LIST_OF_FILE_ARGS[@]}"
 #echo "Debug: OTHER_OPTIONS: ${OTHER_OPTIONS[@]}"
@@ -328,73 +327,89 @@ fi
 
 export RUST_BACKTRACE=full
 
+if  [[ "$wants_print_help" == "1" ]]; then
+   print_help
+    [[ "$IS_SOURCED" == "1" ]] && return "$EXIT_SCRIPT" || exit "$EXIT_SCRIPT"
+fi
+
+if [ -z "${EXIT_SCRIPT+x}" ]; then
+    :
+else
+    [[ "$IS_SOURCED" == "1" ]] && return "$EXIT_SCRIPT" || exit "$EXIT_SCRIPT"
+fi
+
 
 
 # Directory containing the .pl files
 pl_directory="metta_vspace/$PYSWIP_VERSION"
 
 # Initialize a flag to check if any file is newer or if reference file is missing
-should_compile=0
-never_compile=0
 
 if [[ $never_compile -eq 0 ]]; then
 # Reference file
+    reference_file=$(find . -maxdepth 1 -type f -name "Sav.MeTTaLog*" -not -name "*.*" -printf "%T@ %p\n" | sort -k1,1nr | head -n 1 | cut -f2- -d" ")
+    if [[ -z "$reference_file" ]]; then
+      reference_file="./Sav.MeTTaLog"
+    fi
+
+    # Check if Sav.MeTTaLog exists
+    if [[ ! -e "$reference_file" ]]; then
+	echo "Reference file $reference_file does not exist. Compiler will be called."
+	should_compile=1
+    else
+	# Iterate over each .pl file to check if it's newer
+	for pl_file in "$pl_directory"/*_*.pl; do
+	    if [[ ! -e "$pl_file" ]]; then
+		echo "No matching .pl files found in $pl_directory."
+		#exit 1
+	    fi
+
+	    # Check if this .pl file is newer than the reference file
+	    if [[ "$pl_file" -nt "$reference_file" ]]; then
+		echo "$pl_file is newer than $reference_file."
+		should_compile=1
+		break  # No need to check further, exit loop
+	    fi
+	done
+    fi
+
+
+    # If any newer file found or reference file missing, call the compiler
+    if [[ $should_compile -eq 1 ]]; then
+	#if [[ -f "$reference_file" ]]; then
+	#    echo "Calling compiler from $reference_file..."
+	#	swipl -x $reference_file -g qsave_program -g halt
+	#else
+	rm -f $reference_file
+	if [[ "$never_compile" -eq 0 ]]; then
+	    echo "Compiling $reference_file"
+	    swipl -l metta_vspace/$PYSWIP_VERSION/metta_interp.pl -g qcompile_mettalog -- --exeout=$reference_file
+	fi
+    fi
+fi
+
 reference_file=$(find . -maxdepth 1 -type f -name "Sav.MeTTaLog*" -not -name "*.*" -printf "%T@ %p\n" | sort -k1,1nr | head -n 1 | cut -f2- -d" ")
 if [[ -z "$reference_file" ]]; then
   reference_file="./Sav.MeTTaLog"
 fi
 
-# Check if Sav.MeTTaLog exists
-if [[ ! -e "$reference_file" ]]; then
-    echo "Reference file $reference_file does not exist. Compiler will be called."
-    should_compile=1
-else
-    # Iterate over each .pl file to check if it's newer
-    for pl_file in "$pl_directory"/*_*.pl; do
-        if [[ ! -e "$pl_file" ]]; then
-            echo "No matching .pl files found in $pl_directory."
-            #exit 1
-        fi
 
-        # Check if this .pl file is newer than the reference file
-        if [[ "$pl_file" -nt "$reference_file" ]]; then
-            echo "$pl_file is newer than $reference_file."
-            should_compile=1
-            break  # No need to check further, exit loop
-        fi
-    done
-fi
-
-
-# If any newer file found or reference file missing, call the compiler
-if [[ $should_compile -eq 1 ]]; then
-    #if [[ -f "$reference_file" ]]; then
-    #    echo "Calling compiler from $reference_file..."
-    #	swipl -x $reference_file -g qsave_program -g halt
-    #else
-        rm -f $reference_file
-        echo "Calling compiler..."
-	echo swipl -l metta_vspace/$PYSWIP_VERSION/metta_interp.pl -g qcompile_mettalog
-    #fi
-fi
-
-reference_file=$(find . -maxdepth 1 -type f -name "Sav.MeTTaLog*" -not -name "*.*" -printf "%T@ %p\n" | sort -k1,1nr | head -n 1 | cut -f2- -d" ")
-if [[ -z "$reference_file" ]]; then
-  reference_file="./Sav.MeTTaLog"
-fi
 
 if [[ -f "$reference_file" ]]; then
   MLOG="$reference_file --"
-  MLOG="swipl -x $reference_file  ${SWI_OPTIONS[*]} --"
-  MLOG="swipl ${SWI_OPTIONS[*]} -l $METTALOG_DIR/metta_vspace/$PYSWIP_VERSION/metta_interp.pl --"
+  if [[ "${#SWI_OPTIONS[@]}" -gt 0 ]]; then
+       MLOG="swipl -x $reference_file  ${SWI_OPTIONS[*]} --"
+  fi
+  if [[ "$never_compile" -eq 1 ]]; then
+       MLOG="swipl ${SWI_OPTIONS[*]} -l $METTALOG_DIR/metta_vspace/$PYSWIP_VERSION/metta_interp.pl --"
+  fi
 else
   MLOG="swipl ${SWI_OPTIONS[*]} -l $METTALOG_DIR/metta_vspace/$PYSWIP_VERSION/metta_interp.pl --"
 fi
 
-fi
 
 
-METTA_CMD="$MLOG --python=$python_flag ${OTHER_OPTIONS[*]}"
+METTA_CMD="$MLOG --python=$python_flag ${PRE_OTHER_OPTIONS[*]} ${OTHER_OPTIONS[*]}"
 
 OS=$(uname)
 TIMEOUT_CMD="timeout"
@@ -409,36 +424,52 @@ if [[ "$OS" == "Darwin" ]]; then
     fi
 fi
 
+# Initialize the variable to store the exit status of METTA_CMD
+METTA_CMD_EXIT_STATUS=666
+
+# Set a trap to ensure stty sane is run on script exit or interruption
+cleanup() {
+    stty sane
+    if [[ -f "$TEMP_EXIT_CODE_FILE" ]]; then
+        METTA_CMD_EXIT_STATUS=$(<"$TEMP_EXIT_CODE_FILE")
+        rm -f "$TEMP_EXIT_CODE_FILE"
+    else
+        METTA_CMD_EXIT_STATUS=${METTA_CMD_EXIT_STATUS:-$?}
+    fi
+    echo "Exit code of METTA_CMD: $METTA_CMD_EXIT_STATUS"
+    [[ $IS_SOURCED -eq 1 ]] && return $METTA_CMD_EXIT_STATUS || exit $METTA_CMD_EXIT_STATUS
+}
+
+
 if [[ -n "$TIMEOUT" && "$TIMEOUT" -gt 0 ]]; then
-  : #  METTA_CMD="$TIMEOUT_CMD --foreground --preserve-status --signal=SIGTERM --kill-after=5s $TIMEOUT ${METTA_CMD}"
+  trap cleanup EXIT TERM
+   METTA_CMD="$TIMEOUT_CMD --foreground --preserve-status --signal=SIGTERM --kill-after=5s $TIMEOUT ${METTA_CMD}"
 fi
 
 # Conditional to check if html_flag is enabled
-(
 if [[ "$html_flag" == "enable" ]]; then
     export TEE_FILE=${TEE_FILE:-"$METTALOG_DIR/TEE.ansi"}
     touch "$TEE_FILE"
     chmod 777 "$TEE_FILE"
     cat /dev/null > "$TEE_FILE"
 
-    ( export TYPESCRIPT=1
+    export TYPESCRIPT=1
 
 	if [[ "$OS" == "Darwin" ]]; then
 	    # macOS
 	    /usr/bin/script -q -f -a "$TEE_FILE" "$METTA_CMD"
-	    stty sane
+	    echo $? > "$TEMP_EXIT_CODE_FILE"
+	    cleanup
 	else
 	    # Assume Linux
 	    /usr/bin/script -q -f --force -e -a "$TEE_FILE" -c "$METTA_CMD"
-	    stty sane
+	    echo $? > "$TEMP_EXIT_CODE_FILE"
+	    cleanup
 	fi
 
-    ) || true
-    stty sane
 else
-  ((eval $METTA_CMD) || true)
+
+   exec $METTA_CMD
 fi
-) || true
-stty sane
 
 
